# Stock prediction using Time series analysis

In this programm we are going to use a decision tree algorithm to predict if the price of the stock will decrease o increase

## Importing libraries and data

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import pandas as pd

In [3]:
amazon = pd.read_csv('D:/Documentos/Master/temariomaster/p6.DescriptiveMachineLearning/Stockprediction/amzn.csv')
amazon

Date         Open         High          Low        Close  \
0     1997-05-15     2.437500     2.500000     1.927083     1.958333   
1     1997-05-16     1.968750     1.979167     1.708333     1.729167   
2     1997-05-19     1.760417     1.770833     1.625000     1.708333   
3     1997-05-20     1.729167     1.750000     1.635417     1.635417   
4     1997-05-21     1.635417     1.645833     1.375000     1.427083   
...          ...          ...          ...          ...          ...   
5660  2019-11-11  1778.000000  1780.000000  1767.130005  1771.650024   
5661  2019-11-12  1774.660034  1786.219971  1771.910034  1778.000000   
5662  2019-11-13  1773.390015  1775.000000  1747.319946  1753.109985   
5663  2019-11-14  1751.430054  1766.589966  1749.560059  1754.599976   
5664  2019-11-15  1760.050049  1761.680054  1732.859985  1739.489990   

        Adj Close    Volume  
0        1.958333  72156000  
1        1.729167  14700000  
2        1.708333   6106800  
3        1.635417   5467200  
4        1.427083  18853200  
...           ...       ...  
5660  1771.650024   1946000  
5661  1778.000000   2037600  
5662  1753.109985   2989500  
5663  1754.599976   2264800  
5664  1739.489990   3927600  

[5665 rows x 7 columns]

## Preprocess the data

In [4]:
#set date as index
amazon = amazon.set_index(pd.DatetimeIndex(amazon['Date'].values))
amazon

Date         Open         High          Low        Close  \
1997-05-15  1997-05-15     2.437500     2.500000     1.927083     1.958333   
1997-05-16  1997-05-16     1.968750     1.979167     1.708333     1.729167   
1997-05-19  1997-05-19     1.760417     1.770833     1.625000     1.708333   
1997-05-20  1997-05-20     1.729167     1.750000     1.635417     1.635417   
1997-05-21  1997-05-21     1.635417     1.645833     1.375000     1.427083   
...                ...          ...          ...          ...          ...   
2019-11-11  2019-11-11  1778.000000  1780.000000  1767.130005  1771.650024   
2019-11-12  2019-11-12  1774.660034  1786.219971  1771.910034  1778.000000   
2019-11-13  2019-11-13  1773.390015  1775.000000  1747.319946  1753.109985   
2019-11-14  2019-11-14  1751.430054  1766.589966  1749.560059  1754.599976   
2019-11-15  2019-11-15  1760.050049  1761.680054  1732.859985  1739.489990   

              Adj Close    Volume  
1997-05-15     1.958333  72156000  
1997-05-16     1.729167  14700000  
1997-05-19     1.708333   6106800  
1997-05-20     1.635417   5467200  
1997-05-21     1.427083  18853200  
...                 ...       ...  
2019-11-11  1771.650024   1946000  
2019-11-12  1778.000000   2037600  
2019-11-13  1753.109985   2989500  
2019-11-14  1754.599976   2264800  
2019-11-15  1739.489990   3927600  

[5665 rows x 7 columns]

In [5]:
amazon.index.name = 'Date'
amazon

Date         Open         High          Low        Close  \
Date                                                                         
1997-05-15  1997-05-15     2.437500     2.500000     1.927083     1.958333   
1997-05-16  1997-05-16     1.968750     1.979167     1.708333     1.729167   
1997-05-19  1997-05-19     1.760417     1.770833     1.625000     1.708333   
1997-05-20  1997-05-20     1.729167     1.750000     1.635417     1.635417   
1997-05-21  1997-05-21     1.635417     1.645833     1.375000     1.427083   
...                ...          ...          ...          ...          ...   
2019-11-11  2019-11-11  1778.000000  1780.000000  1767.130005  1771.650024   
2019-11-12  2019-11-12  1774.660034  1786.219971  1771.910034  1778.000000   
2019-11-13  2019-11-13  1773.390015  1775.000000  1747.319946  1753.109985   
2019-11-14  2019-11-14  1751.430054  1766.589966  1749.560059  1754.599976   
2019-11-15  2019-11-15  1760.050049  1761.680054  1732.859985  1739.489990   

              Adj Close    Volume  
Date                               
1997-05-15     1.958333  72156000  
1997-05-16     1.729167  14700000  
1997-05-19     1.708333   6106800  
1997-05-20     1.635417   5467200  
1997-05-21     1.427083  18853200  
...                 ...       ...  
2019-11-11  1771.650024   1946000  
2019-11-12  1778.000000   2037600  
2019-11-13  1753.109985   2989500  
2019-11-14  1754.599976   2264800  
2019-11-15  1739.489990   3927600  

[5665 rows x 7 columns]

### Now we are going to create a column that will say if the price has increase or decrease, that is the label column

We are going to do that by creating a column that compares the prices of the past day to todays one, if the price is lower set 0 if it is higher set 1

In [8]:
amazon['Price_Up'] = np.where(amazon['Close'].shift(-1) > amazon['Close'], 1, 0)

In [9]:
amazon

Date         Open         High          Low        Close  \
Date                                                                         
1997-05-15  1997-05-15     2.437500     2.500000     1.927083     1.958333   
1997-05-16  1997-05-16     1.968750     1.979167     1.708333     1.729167   
1997-05-19  1997-05-19     1.760417     1.770833     1.625000     1.708333   
1997-05-20  1997-05-20     1.729167     1.750000     1.635417     1.635417   
1997-05-21  1997-05-21     1.635417     1.645833     1.375000     1.427083   
...                ...          ...          ...          ...          ...   
2019-11-11  2019-11-11  1778.000000  1780.000000  1767.130005  1771.650024   
2019-11-12  2019-11-12  1774.660034  1786.219971  1771.910034  1778.000000   
2019-11-13  2019-11-13  1773.390015  1775.000000  1747.319946  1753.109985   
2019-11-14  2019-11-14  1751.430054  1766.589966  1749.560059  1754.599976   
2019-11-15  2019-11-15  1760.050049  1761.680054  1732.859985  1739.489990   

              Adj Close    Volume  Price_Up  
Date                                         
1997-05-15     1.958333  72156000         0  
1997-05-16     1.729167  14700000         0  
1997-05-19     1.708333   6106800         0  
1997-05-20     1.635417   5467200         0  
1997-05-21     1.427083  18853200         0  
...                 ...       ...       ...  
2019-11-11  1771.650024   1946000         1  
2019-11-12  1778.000000   2037600         0  
2019-11-13  1753.109985   2989500         1  
2019-11-14  1754.599976   2264800         0  
2019-11-15  1739.489990   3927600         0  

[5665 rows x 8 columns]

In [11]:
#check null values
amazon.isnull().values.any()

False

In [13]:
#delete date column
del amazon['Date']
amazon

Open         High          Low        Close    Adj Close  \
Date                                                                          
1997-05-15     2.437500     2.500000     1.927083     1.958333     1.958333   
1997-05-16     1.968750     1.979167     1.708333     1.729167     1.729167   
1997-05-19     1.760417     1.770833     1.625000     1.708333     1.708333   
1997-05-20     1.729167     1.750000     1.635417     1.635417     1.635417   
1997-05-21     1.635417     1.645833     1.375000     1.427083     1.427083   
...                 ...          ...          ...          ...          ...   
2019-11-11  1778.000000  1780.000000  1767.130005  1771.650024  1771.650024   
2019-11-12  1774.660034  1786.219971  1771.910034  1778.000000  1778.000000   
2019-11-13  1773.390015  1775.000000  1747.319946  1753.109985  1753.109985   
2019-11-14  1751.430054  1766.589966  1749.560059  1754.599976  1754.599976   
2019-11-15  1760.050049  1761.680054  1732.859985  1739.489990  1739.489990   

              Volume  Price_Up  
Date                            
1997-05-15  72156000         0  
1997-05-16  14700000         0  
1997-05-19   6106800         0  
1997-05-20   5467200         0  
1997-05-21  18853200         0  
...              ...       ...  
2019-11-11   1946000         1  
2019-11-12   2037600         0  
2019-11-13   2989500         1  
2019-11-14   2264800         0  
2019-11-15   3927600         0  

[5665 rows x 7 columns]

## Train and test the model

In [22]:
# getting X and y data
X = amazon.iloc[:,0:6].values
X

array([[2.43750000e+00, 2.50000000e+00, 1.92708300e+00, 1.95833300e+00,
        1.95833300e+00, 7.21560000e+07],
       [1.96875000e+00, 1.97916700e+00, 1.70833300e+00, 1.72916700e+00,
        1.72916700e+00, 1.47000000e+07],
       [1.76041700e+00, 1.77083300e+00, 1.62500000e+00, 1.70833300e+00,
        1.70833300e+00, 6.10680000e+06],
       ...,
       [1.77339001e+03, 1.77500000e+03, 1.74731995e+03, 1.75310999e+03,
        1.75310999e+03, 2.98950000e+06],
       [1.75143005e+03, 1.76658997e+03, 1.74956006e+03, 1.75459998e+03,
        1.75459998e+03, 2.26480000e+06],
       [1.76005005e+03, 1.76168005e+03, 1.73285999e+03, 1.73948999e+03,
        1.73948999e+03, 3.92760000e+06]])

In [21]:
y = amazon.iloc[:,6].values
y

array([0, 0, 0, ..., 1, 0, 0])

In [23]:
# Getting train and testing data with 80-20% proportion
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2) 

In [26]:
tree = DecisionTreeClassifier()


In [27]:
tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [29]:
print(tree.score(X_train,y_train))

1.0


In [31]:
tree_predictions = tree.predict(X_test)

In [33]:
print(tree_predictions)

[0 1 1 ... 0 0 0]


In [34]:
y_test

array([1, 0, 0, ..., 1, 1, 1])

## Test and Train using grid search cross validation

In [35]:
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(n_splits=1,test_size=0.3,random_state=13)

In [36]:
for train_index, test_index in sss.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [46]:
params = {'criterion':["gini", "entropy"], 
                                  'max_depth':[None,3,5,7,9],
                                  'min_samples_split':[2,4,8,16,20]}


In [47]:
from sklearn.model_selection import GridSearchCV
miModelo = DecisionTreeClassifier()
gs = GridSearchCV(estimator=miModelo,param_grid=params,scoring='accuracy',cv=5,verbose=1)

In [48]:
gs.fit(X_train,y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 3, 5, 7, 9],
                         'min_samples_split': [2, 4, 8, 16, 20]},
             scoring='accuracy', verbose=1)

In [49]:
resultsCV = gs.cv_results_
resultsCV

{'mean_fit_time': array([0.04506121, 0.04099479, 0.03918624, 0.03804226, 0.03781934,
        0.00668025, 0.00576258, 0.0059967 , 0.00528107, 0.00665903,
        0.00892296, 0.00932293, 0.01027288, 0.00952835, 0.00965185,
        0.01249642, 0.01285501, 0.01282105, 0.01298943, 0.01291003,
        0.01645198, 0.01603546, 0.01629505, 0.01689434, 0.0246181 ,
        0.10388494, 0.10091658, 0.10468044, 0.10322461, 0.09783554,
        0.00892339, 0.0090044 , 0.01043935, 0.01001735, 0.00999608,
        0.01510115, 0.01572905, 0.01416631, 0.01502242, 0.01425996,
        0.02094188, 0.02114458, 0.01952858, 0.02056799, 0.02132788,
        0.02569008, 0.02691207, 0.02574062, 0.02564073, 0.02611532]),
 'std_fit_time': array([0.00619848, 0.00562303, 0.00479257, 0.00475912, 0.00432572,
        0.00143074, 0.0016834 , 0.0018341 , 0.00165371, 0.0014929 ,
        0.00113003, 0.00194336, 0.00204046, 0.00182441, 0.00194219,
        0.00173417, 0.00161245, 0.00080001, 0.00127342, 0.00098012,
        0.000

In [50]:
clfBest = gs.best_estimator_
clfBest

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_split=4)

In [51]:
clfBest.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_split=4)

In [52]:
y_pred = clfBest.predict(X_test)

In [53]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))


0.5023529411764706
